In [4]:
import pandas as pd
csv_df = pd.read_csv('cars.csv')

csv_df.head()

Car;MPG;Cylinders;Displacement;Horsepower;Weight;Acceleration;Model;Origin
0  Chevrolet Chevelle Malibu;18.0;8;307.0;130.0;3...                        
1  Buick Skylark 320;15.0;8;350.0;165.0;3693.;11....                        
2  Plymouth Satellite;18.0;8;318.0;150.0;3436.;11...                        
3  AMC Rebel SST;16.0;8;304.0;150.0;3433.;12.0;70;US                        
4    Ford Torino;17.0;8;302.0;140.0;3449.;10.5;70;US

In [18]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]],dtype=np.float32)
print (a.ndim, a.shape, a.dtype)
b = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,1,2]]],dtype=np.float32)
print (b.ndim, b.shape)
c = np.array([4,5,6], ndmin=6)
print (c.ndim, c.shape)

2 (2, 3) float32
3 (2, 2, 3)
6 (1, 1, 1, 1, 1, 3)


In [30]:
a = np.array([1,2,3,4,5,6])
print (a)
a = a.reshape(3,2)
print (a)
a = a.reshape(2,-1)
print (a)
a = a.ravel()
print (a)
print ('break')
a = np.arange(10).reshape(5,2)
print (a)
a = a.T
print (a)
a = a.transpose((1,0))
print (a)
print ('break')
print (np.sqrt(a))

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
break
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 2 4 6 8]
 [1 3 5 7 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
break
[[0.         1.        ]
 [1.41421356 1.73205081]
 [2.         2.23606798]
 [2.44948974 2.64575131]
 [2.82842712 3.        ]]
